name: spsbrats
favicon: null
layout_spectrum: 0.012212258065119386
typography_spectrum: 0.24426004686392844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.13681840524077415
  lightness: 0.0027652252465486526
  saturation: 0.5052656361367553
  rhythmicContrast: 0.6949978524353355
purpose: []
